// Generated by CoffeeScript 1.3.3
(function() {
  var bindPrint, cancelLazyload, createDialog, cstypo, fixSidebar, notifications, printPage, protectEmails, protectImgs, togglable, videos;

  protectEmails = function() {
    return $('.em').filter('[data-em]').each(function() {
      var e, t;
      t = $(this);
      e = t.data('em').replace('/', '@');
      return t.attr('href', 'mailto:' + e).not('.custom-text').text(e);
    });
  };

  window.equalHeight = function(container) {
    return container.each(function() {
      var thisCont;
      thisCont = $(this);
      return thisCont.imagesLoaded(function() {
        return window.equalHeightDo(thisCont.children());
      });
    });
  };

  window.equalHeightDo = function(children) {
    var tallest;
    tallest = 0;
    children.each(function() {
      var th;
      th = $(this).height();
      if (tallest < th) {
        return tallest = th;
      }
    });
    children.height(tallest);
    return tallest;
  };

  togglable = function() {
    $('.toggle').on('click', function(e) {
      e.preventDefault();
      return $(this).toggleClass('in').next('.togglable').toggleClass('in');
    });
    return $('.togglable').on('click', '.close', function() {
      return $(this).parents('.togglable').toggleClass('in').prev('.toggle').toggleClass('in');
    });
  };

  fixSidebar = function() {
    var d;
    d = $('#detail');
    if (d.length === 1) {
      return d.css({
        minHeight: d.children('#detail-right').outerHeight() + 36
      });
    }
  };

  protectImgs = function() {
    return $('#tab-images').on('contextmenu', 'img', function(e) {
      e.preventDefault();
      return false;
    });
  };

  createDialog = function(el) {
    return el.dialog({
      modal: true,
      width: 335,
      draggable: false,
      resizable: false,
      minHeight: 0,
      open: function() {
        return $(this).parents('.ui-dialog').css({
          left: '50%',
          marginLeft: -335 / 2
        });
      },
      close: function() {
        return $(this).remove();
      }
    });
  };

  notifications = function() {
    var n;
    n = $('#notification-src');
    $('body').on('click', '.ui-widget-overlay, .ui-dialog .close.ico-close', function() {
      return $('.ui-dialog-titlebar-close').trigger('click');
    });
    if (n.length === 1) {
      n.append('<span class="close ico-close"></span>');
      return createDialog(n);
    }
  };

  videos = function() {
    var resizeRatio, swfLocation, wrap;
    swfLocation = "" + window.baseUrl + "/viewers/apps/flowplayer-3.2.7.swf";
    wrap = $('#detail-left');
    resizeRatio = function(el, wrap) {
      var r;
      r = parseFloat(el.data('ratio'));
      return el.css({
        display: 'block',
        width: wrap.width(),
        height: wrap.width() / r
      });
    };
    $('.video-me').each(function() {
      var id, t;
      t = $(this);
      id = t.attr('id');
      if (t.is('.ratio-resize[data-ratio]')) {
        resizeRatio(t, wrap);
      }
      return flowplayer(id, swfLocation);
    });
    return $(window).on('resize', function() {
      return $('.ratio-resize').filter('[data-ratio]').each(function() {
        return resizeRatio($(this), wrap);
      });
    });
  };

  cstypo = function() {
    if ($('html').hasClass('lang-cs')) {
      return $('p, li, div').add('.footer-left a').cstypo();
    }
  };

  cancelLazyload = function() {
    $('.lazyload').trigger('appear');
    if (typeof window.loadImg !== 'undefined') {
      return window.loadImg($('ul li', '#tab-images'));
    }
  };

  printPage = function(notification) {
    var element;
    element = $('<div class="notification"></div>').html(notification).append('<span class="close ico-close"></span>');
    createDialog(element);
    cancelLazyload();
    return window.print();
  };

  bindPrint = function() {
    return $('body').on('click', '.print-page', function() {
      return printPage($(this).data('notification'));
    });
  };

  $(function() {
    window.equalHeight($('.equal-height, .grid > ul'));
    fixSidebar();
    cstypo();
    notifications();
    protectImgs();
    togglable();
    videos();
    protectEmails();
    return bindPrint();
  });

}).call(this);
