// Generated by CoffeeScript 1.3.3
(function() {
  var carouselAdapt, carouselAdaptive, initCarousel, initDarkScroll;

  carouselAdapt = function() {
    var ow, tw;
    ow = $(window).width();
    tw = ow - 330 - 300 - 20;
    if (tw > 620) {
      tw = 620;
    }
    return window.carouselImages.width(tw);
  };

  carouselAdaptive = function() {
    carouselAdapt();
    return $(window).bind('resize', carouselAdapt());
  };

  initCarousel = function() {
    var height, hf, settings, wrap;
    wrap = $('ul', '#home-featured');
    if (wrap.length !== 1) {
      return false;
    }
    hf = $('#home-featured');
    height = wrap.find('.img').width();
    settings = {
      width: hf.width(),
      height: height,
      responsive: true,
      pagination: {
        container: '#home-featured-pagination'
      },
      scroll: {
        fx: 'crossfade',
        pauseOnHover: true
      },
      auto: {
        play: true,
        pauseDuration: 4000
      },
      items: {
        visible: 1,
        width: wrap.width()
      }
    };
    wrap.carouFredSel(settings);
    return $(window).on('resize load', function() {
      var set;
      set = {
        items: {
          width: hf.width()
        },
        height: wrap.find('.img').width(),
        width: hf.width()
      };
      return wrap.trigger('configuration', set);
    });
  };

  initDarkScroll = function() {
    var settings, wrap;
    wrap = $('ul', '#home-dark');
    if (wrap.length !== 1) {
      return false;
    }
    if (!(wrap.find('li').length < 3)) {
      return false;
    }
    settings = {
      width: '100%',
      infinite: false,
      circural: false,
      align: 'left',
      padding: [0, 20, 0, 20],
      scroll: {
        items: 2
      },
      prev: {
        button: '#home-dark-left'
      },
      next: {
        button: '#home-dark-right'
      },
      auto: {
        play: false
      },
      items: {
        width: 380
      }
    };
    return wrap.carouFredSel(settings);
  };

  $(function() {
    window.carouselImages = $('.img', '#home-featured');
    initCarousel();
    return initDarkScroll();
  });

}).call(this);
