// Generated by CoffeeScript 1.3.3
(function() {
  var bindEditor, moveEditor;

  moveEditor = function() {
    var s, w;
    w = $('#my-collections-editor');
    s = $('.sidebar', '#main');
    if (w.length === 1 && s.length === 1) {
      return s.append(w);
    }
  };

  bindEditor = function() {
    var forms, wrap;
    forms = {
      editF: $('#my-collections-form'),
      newF: $('#my-collections-form-new')
    };
    forms.both = forms.editF.add(forms.newF);
    wrap = $('#my-collections-toggles');
    return wrap.on('click', 'a', function(e) {
      var t;
      e.preventDefault();
      t = $(this);
      if (t.hasClass('current')) {
        wrap.find('a').removeClass('current');
      } else {
        wrap.find('a').removeClass('current');
        t.addClass('current');
      }
      if (t.is('#my-collections-edit')) {
        forms.newF.removeClass('in');
        return forms.editF.toggleClass('in');
      } else {
        forms.editF.removeClass('in');
        return forms.newF.toggleClass('in');
      }
    });
  };

  $(function() {
    moveEditor();
    return bindEditor();
  });

}).call(this);
