// Generated by CoffeeScript 1.3.3
(function() {
  var initFilter;

  initFilter = function() {
    var c, i, s, w;
    w = $('#splashBrowsePanelContent');
    s = $('#browsePanelSearchInput', '#splashBrowsePanel');
    i = $('.browseSelectPanelLink', '#splashBrowsePanel');
    c = $('#itemsNumberSpan');
    c.text(i.length);
    return s.on('keyup', function() {
      var f, v;
      if (!w.hasClass('working')) {
        f = i;
        w.addClass('working');
        v = $(this).val();
        if (v === '') {
          f.removeClass('hidden');
        } else {
          i.addClass('hidden');
          f = i.filter(function() {
            return $(this).text().toLowerCase().indexOf(v) >= 0;
          });
          f.removeClass('hidden');
        }
        c.text(f.length);
        return w.removeClass('working');
      }
    });
  };

  initFilter();

}).call(this);
