// Generated by CoffeeScript 1.3.3
(function() {
  var initTree;

  initTree = function() {
    window.tree = {};
    window.tree.wrap = $('ul', '#hierarchy-full');
    window.tree.parents = window.tree.wrap.find('.parent');
    window.tree.wrap.on('click', '.open > .icons', function(e) {
      var li;
      e.stopPropagation();
      li = $(this).parent('.parent');
      if (li.hasClass('closed')) {
        return;
      }
      return li.addClass('closed');
    });
    return window.tree.wrap.on('click', '.open.closed > .icons', function(e) {
      var li;
      e.stopPropagation();
      li = $(this).parent('.parent');
      return li.removeClass('closed');
    });
  };

  $(function() {
    return initTree();
  });

}).call(this);
